- examples/transmission_main_example.py
Removed the invalid source/destination node error message part that said "did you mean: \n{nodes_suggestion}?" because 1) there is anyway no possibility to answer the question and 2) when nodes_suggestion is empty it just looks strange.
Also tried to simplify the source and destination assignment a bit - please have a look that it still does the same thing.
> source and destination handling i transmission main example

- gnpy/core/network.py
Some small modifications in the `split_fiber` function in `network.py`:
- It's not necessary to remove edges since removing a node also removes all adjacent edges.
- It's not necessary to add nodes since adding edges between nodes also adds the nodes.
- Also update `Fiber.params.length` for new spans. Before only `Fiber.length` was updated which means `Fiber.params.length` and `Fiber.length` were inconsistent.
- Change numbering of spans in fiber uids from (0/n to (n-1)/n) to less confusing (1/n to n/n).
> Some modifications in split_fiber function

- README.rst
Fix a couple of broken links in the README.
Add NZDF to the fiber library description.
> fix broken links in readme

- gnpy/core/elements.py
This reverts a previous small change that accidentally led to all Edfas having effective gain = 0 in gain mode.
> gain-mode fix

- examples/path_requests_run.py
- examples/transmission_main_example.py
Small change of the handling of the optional `--verbose` argument in example scripts. With this change, when the count is higher than the highest specified level (currently `2: DEBUG`), the logging is set to the highest level instead of the lowest level (`0: CRITICAL` or `ERROR`)  as before. (Note that before, `args.verbose` was never actually set to `0` since no `--verbose` argument defaulted to `args.verbose=None`).
Also remove some unnecessary default values.
> handling of --verbose

- examples/transmission_main_example.py
> Fix a typo of log message in transmission_main_example.py

- README.rst
- examples/eqpt_config.json
- gnpy/core/equipment.py
- gnpy/core/info.py
- gnpy/core/request.py
- tests/data/eqpt_config.json
- tests/test_amplifier.py
This adds support for a Tx OSNR parameter, see #116. ASE noise out from the transponder is set in the `create_input_spectral_information` function according to this parameter.
The Tx OSNR parameter is defined in `eqpt_config.json`. Currently it is set to a high value, 45 dB, both in SI default and in all trx modes.
So far, no distinction is made between in-band and out-of-band Tx OSNR. Penalty due to ASE noise from other transponders and filterless add/drop is not taken into account.
> Add Tx OSNR

- examples/path_requests_run.py
- gnpy/core/convert.py
- gnpy/core/network.py
- gnpy/core/request.py
Several fixes handling some bugs
- output file of -o option in path_requests_run.py was not correctly
handled in case of path indirection eg ../../bar.foo
- fiber constraint is not correctly handled in case of several parrallel directions
of same fiber name. remove if from the set of constraint till problem is not solved
This will need additional work to be compliant with fiber constraint
- loose_list was not correctly indexed in request.py. assume the first element attribute (except
of the transceiver) applies for the whole list. 
This is a fast patch and will need further corrections to handle a detail per node loose definition
- handle the case when path.snr is none in the optimization of mode process
maybe addresses part of #178 
- a cutoff value needed when networks have a great …
> Corrections

- examples/eqpt_config.json
- examples/meshTopologyExampleV2.json
- examples/path_requests_run.py
- gnpy/core/elements.py
- gnpy/core/equipment.py
- gnpy/core/info.py
- gnpy/core/request.py
- gnpy/core/utils.py
- tests/data/eqpt_config.json
- tests/test_amplifier.py
- tests/test_automaticmodefeature.py
Tx_OSNR added at the end of propagation
Terminal ROADM add drop OSNR contribution (in eqpt_config / ROADM)
System margins contribution (in eqpt_config / SI)
code cleaning for the SI function
> Sys margins

- gnpy/core/network.py
- gnpy/core/request.py
Could you please have a look on this work ?
I have been requested several time to provide path computation on the length (km) basis instead of hop.
Here is what I propose to integrate this: 
I have added weigths on network edge in order to compute shortest path in length (km) and not in hop. 
- dijkstra_path with weight attribute
- sort all_simple_paths results as a function of paths' length instead of hop
Note that the feature only works with updated Networkx module. I have not made this change optional since in optical networks length is more relevant than hops.
> Add weight edge

- README.rst
The table was completely hidden from the HTML rendering at GitHub. The space between the "left edge" of the table and the text content appears to be substantial.
> Fix RST syntax in the ROADM table

- AUTHORS.rst
- docs/index.rst
These two lists were not synced with each other, and some contributors whose commits have been merged in git were missing. The resulting list is a bit longer because not everybody who contributes does that strictly via commits pushed to GitHub.
Dear previously unlisted contributos (@diegolaunch , @MiquelGA , @szhu3210 ), are you OK with being listed here?
> Add all missing authors and sync the two lists of contributors

- .codecov.yml
The results are still perfectly visible within the *Checks* tab, so let's cut the comment spam a little bit.
I've already done the same for lgtm.com; for that app, it's done in their service's configuration within the web app.
> CI: Disable Codecov comments

- pytest.ini
- requirements.txt
For some reason, warnings were disabled in commit 07de78c, but it is not clear to me what the purpose was back then. It passes without warnings locally, and I think that warnings are useful in general, so let's give the CI a try.
> tests: re-enable warnings

- README.rst
Due to a misaligned `|`, the table was not rendered at all in the GitHub overview.
Thanks to @ggrammel for catching this in his brownfield doc.
> docs: Fix rendering of the SpectralInformation docs

- examples/path_requests_run.py
- examples/transmission_main_example.py
- gnpy/core/ansi_escapes.py
- gnpy/core/elements.py
- gnpy/core/equipment.py
- gnpy/core/exceptions.py
- gnpy/core/network.py
The code was originally written with direct `exit()` invocation in order to present nice error messages to the user who is running examples from our `examples/` directory. However, this means that one cannot really use the library *as a library*, handling errors in a completely different manner. As an example, if someone wants to write a PCE server with GNPy for impairment calculation, it is most certainly a wrong thing to do to hard-exit an entire daemon when handling a malformed request.
This patch series therefore introduces some rudimentary exception hierarchy, and then we add some pretty-printers for colorful printing in our examples. It already distinguishes between "equipment library errors" (malformed data) and "network topology errors" (nonsensical topologies).
(My editor …
> Use exceptions instead of `sys.exit()` when reporting configuration errors

- .travis.yml
I misunderstood how Travis CI works; it's not a subshell, it's something which affects the other commands. Let's just run everything from the top-level directory.
> CI: do not attempt to `cd` twice

- gnpy/core/elements.py
- gnpy/core/info.py
For some reason, the code allowed using "convenience names" for accessing properties since commit 58ac717f. To me, this looks like an obvious anti-pattern because accessing a single property via three different names only makes the code less readable. Let's kill this "feature".
In case of the `Power` class, the code used "ase" and "nli" on the majority of places, so let's use these abbreviations instead of their spelt-out variants.
SpectralInformation was "clean" already, but there were calls to the `update()` wrapper around the `namedtuple._replace`.  Given that there were no property aliases, it's safe to just call `_replace()` directly.
In case of the `Pref` class, once again always use `p_span0`, `p_spani` instead of `p0` and `pi` -- it's a trivial change.
(Also a small trivial but …
> Remove property aliases

- examples/transmission_main_example.py
- gnpy/core/science_utils.py
The Raman engine computes NLI just for a subset of channels; this is an important speed optimization because the computation is rather CPU heavy. However, the code just left NaNs in place for NLI of those channels which were not explicitly simulated.
This is wrong because these NaNs propagate all the way to the total input/output powers per the whole spectrum, etc, leading to NaNs being shown to the user.
This patch uses a very simple linear approximation just in order to prevent these NaNs.
fixes #288
Cc: @aleFerrari
> Raman: linear interpolation of channel NLI

- examples/transmission_main_example.py
- Fix output per-channel SNR when using --show-channels to include contributions from add_drop_osnr and tx_osnr
- Avoid recalculating SNRs in transmission main example since they are already calculated and stored in the Transceiver class
- Also include per channel power (useful for checking tilt) and OSNR ASE in the output
Fixes #290
> Fix per-channel SNR output

- gnpy/core/elements.py
While the `itufl()` function uses THz by default, its values depend on the frequency range that is passed via arguments. In this context, the `f_min` and `f_max` come from the default `SpectralInformation` which is in Hz.
Thanks to @ojnas for reporting this.
fixes #243
> Do not mix THz and Hz

- .docker-entry.sh
- .docker-travis.sh
- .travis.yml
- Dockerfile
A third, independent job in Travis CI just for building a container
image (and testing it a little bit). Here's how to use it once it is
built and published and pulled:
```shell-session
$ docker run -it --rm --volume $(pwd):/shared telecominfraproject/oopt-gnpy
```
One can also pass commands to it directly. Note that the *relative* path specifier given as `./` is required. One could possibly get around it by `$PATH` manipulation, but hey, I have to stop somewhere.
```shell-session
$ docker run -it --rm --volume $(pwd):/shared telecominfraproject/oopt-gnpy ./transmission_main_example.py
```
Thanks to @ojnas for the `--volume` option trick and for that early non-overwriting copying for the `example/` directory.
The `install` phase in Travis CI is apparently common for all jobs in the build …
> Automatic building of Docker images

- json_structure_description.rst
I am not changing the JSON key name now because of the plan to go with a full-blown YANG model (see #266).
fixes #298
> docs: Document Transceiver.mode.OSNR

- examples/path_requests_run.py
- examples/transmission_main_example.py
- gnpy/core/ansi_escapes.py
- gnpy/core/request.py
- tests/test_automaticmodefeature.py
(This replaces #261 by me and #293 by Jonas.)
This is inspired by #293. The original issue was that the transponder OSNR was not accounted for. Rather than making the `propagate()` and `propagate2()` more complex, let's move the actual path printing to the demo code. There's no secret sauce in there, it's just a simple for-each-print thingy, so let's remove it from the library code.
fixes #262
Reading `80000m` is a bit more complex than just `80 km`. Also let's add a space between the numebr and the unit for better readability.
I think that this SNR value represents the most important output of this  example. There's plenty of debugging info on display already, so let's make this one more prominent.
I was thinking about moving the highlighting to elements' each `__str__()` function, but …
> Refactor printing

- README.rst
As per @aleFerrari 's request, this adds a DOI and makes this software citeable. DOIs are assigned automatically via Zenodo in a process that's integrated with GitHub.
> docs: show a DOI

- examples/transmission_main_example.py
Esther and Jonas pointed out that it is much more common to work with OSNR measurements per 0.1nm rather than per signal bandwidth. This is in line with what OSAs usually report and what transponder datasheets specify.
cc #307
> Rework OSNR printing

- gnpy/core/elements.py
- gnpy/core/utils.py
- nuked the unused `itufs`
- better name for the former `itufl`
- remove `itufl`'s defaults, rework the help, etc
> Small refactoring for itufs/utifl

- requirements.txt
Upstream bugreport at sphinx-doc/sphinx#6887 suggests that this is due to pip picking up the 0.16b0.dev0 pre-release...
This is deliberately done on master because this failure affects all branches.
> build: workaround Sphinx doc build failure

- gnpy/core/convert.py
when a node name used in link does not correspond to listed
node names, Bad link msg was thrown without info on which link
causes the problem.
This change gives additional info on link and catch the user error
more cleanly.
Signed-off-by: EstherLerouzic <esther.lerouzic@orange.com>
> Give more useful comment for user to correct topology

- tests/test_amplifier.py
In commit 80eced8, the structure of parameters to `elements.Fiber` was changed. Options such as fiber length are now passed in via `self.parameters.*` instead of `self.*`. Commit 639b379 which fixed a test failure precedes that change, and when we merge both as I did in commit bc4b664, the test no longer works. My bad. On the other hand, this will be caught by [trunk gating](https://zuul-ci.org/docs/zuul/discussion/gating.html) which is something that Zuul can do, and therefore something that we'll have in our upcoming CI, yay!
Fixes: bc4b664 #340
> Fix test failure due to mishandled merge

- .travis.yml
- Dockerfile
- README.rst
Ouch, this one hurts. It turns out that PBR-based setup does *not* install all dependencies when running `python setup.py install`. On the other hand, running any of:
- `pip install .`
- `pip install --editable .`
- `python setup.py develop`
...makes everything work. So, let's change the instructions and all the
build scripts (including the Docker file) to make sure this thing still
works. Sorry for noise.
This is a significant change, it means that people will have "in-place
installations" of GNPy. Changes to their git checkouts, if used, will
apply, etc. I think this is actually a good change.
fixes #287
TL;DR: package installation with Python is still a mess.
> Fix dependency installation with PBR

- .travis.yml
- docs/install.rst
There are several differences between `python setup.py develop` and `pip
install --editable .` ; one which became relevant a few days ago is the fact that `python setup.py develop` is apparently happy to pull in pre-releases of our dependencies -- perhaps due to the fact that this package, when installed from git, is also considered a pre-release. This has led to CI failures in Travis, and for some reason just on Python 3.6, not on Python 3.7.
This is of course rather ugly, and there's no need to start pulling in pre-releases of various pieces of software that we're using, anyway. Fix this by asking our users to use PIP, and adjusting the CI accordingly. Zuul CI uses tox which is documented to call PIP behind the scenes, so there's no change in there.
Fixes: …
> Install via PIP

- requirements.txt
On Travis, builds with Python 3.7 started failing recently:
```
ERROR: pandas 1.2.0 has requirement numpy>=1.16.5, but you'll have numpy 1.16.4 which is incompatible.
ERROR: scipy 1.6.0 has requirement numpy>=1.16.5, but you'll have numpy 1.16.4 which is incompatible.
```
Apparently the version of numpy that gets used when under Travis is rather different among their Python versions, and we get:
- numpy-1.19.4 in their Python 3.8.6 env,
- numpy-1.19.0 on 3.6.7,
- numpy-1.16.4 on 3.7.1
That's a bit insane to my liking, perhaps they're preloading popular libs such as numpy into their images for speed ups? For comparison, on Zuul CI we have this:
- numpy-1.19.4 with Python 3.8.6 on Fedora 32,
- numpy-1.19.4 with Python 3.6.8 on CentOS 8
Let's start requiring numpy 1.19.4 everywhere. This is …
> Bumpy numpy for Travis CI

- .travis.yml
...because that one obviously doesn't read `bindep.txt`, but it has its own way of installing these dependencies.
> CI: Unbreak Travis

- .codecov.yml
Right now the project homepage on GitHub [shows an red failure](https://codecov.io/gh/Telecominfraproject/oopt-gnpy/commit/924c56850d77c53f8e5c46e21082e5510a8b00d5) due to [1]. While I agree that coverage reports are a useful metric, they are most relevant when considering patches (or changes) on their own. I do not think it makes any sense to show them on branches. When we merged that commit, the reviewer had the info about the coverage change, and we just do not have 100% coverage. Let's not pretend that that is a blocker.
Duplicate of https://review.gerrithub.io/c/Telecominfraproject/oopt-gnpy/+/516001 because I want to see this in the GitHub UI as well.
> CI: do not "fail" branches upon coverage decrease

- .github/workflows/main.yml
- tox.ini
This might be a wee bit controversial, I guess, because the Zuul jobs
look like there's a dedicated playbook for that
(playbooks/python/release.yaml). However, that would be one extra VM
launch, which feels wasteful. Let's waste the CPU cycles elsewhere --
during each "regular test build", produce a wheel as well.
It looks that these "wheels" are *the* format for distributing Python
packages now -- including the source code, of course. Since there's no
real support for tag review in Gerrit, I don't think I need Zuul for
release management, either, so I'll just rely on GitHub actions for
release upload, I guess. And for that, I need to "somehow" create a
wheel anyway, so let's just do this all the time to ensure that it
really works and never stops working.
Change-Id: …
> CI: always try to build a release wheel

- .github/workflows/main.yml
We've been accidentally not updating the `latest` tag on Docker hub after switching from Travis CI to GitHub actions. Traditionally, we've assumed the `latest` points to the "latest release", so this patch makes it simple and will call any pushed "version tag" as the `latest`. This will become a problem if/when we start maintaining multiple releases, but I think it's a safe approach for now.
As before, there's also the `master` tag which always points to the, well, master branch of the repo.
The `.github/` prefix is special, which is why I'm pushing this as a PR instead of going through Gerrit -- that one would break replication.
> CI: docker: releases should update the `latest` tag

- .lgtm.yml
*(Opening a PR so that hopefully LGTM will give me some early feedback before merging this.)*
By default, this service issues a warning for strings which format data like {uid}, flagging this pattern as related to antipatterns CWE-312, CWE-315 and CWE-359. This warning is not relevant for us because we never process sensitive information (if there are some NDA-covered data in the input, well, the user already has them, we're just using these).
Silence this warning (it's currently getting us an B rating, apparently).
See-also: https://lgtm.com/rules/1510014536001/
Change-Id: Id5cdd2c62e61a8329760d3fb79665737beb22378
> Silence an irrelevant warning on LGTM.com

- tests/test_equalization.py
GitHub CI started failing with the following error:
```diff
assert (watt2dbm(si.signal) == target - correction).all()
assert False
+  where False = <built-in method all of numpy.ndarray object at 0x7f01c0ca94d0>()
+    where <built-in method all of numpy.ndarray object at 0x7f01c0ca94d0> = array([-25.5, -24.5, -22.5, -25. , -27.5]) == array([-25.5, -24.5, -22.5, -25. , -27.5])
+array([-25.5, -24.5, -22.5, -25. , -27.5])
-array([-25.5, -24.5, -22.5, -25. , -27.5])
```
This is with code which has passed in the Zuul/Vexxhost CI.
It looks very similar to a regression that hit numpy 1.24.0, but the GitHub action log shows that this happens with numpy 1.24.1. Weird, and I'm not getting these differences locally, and also not on an ARM64 cloud VM.
Anyway, comparing floating point numbers for …
> tests: do not compare floating point numbers for equality

- .github/workflows/main.yml
- requirements.txt
- setup.cfg
- tests/requirements.txt
see the individual commits for a real description
> CI: Python 3.12 and extended platform coverage

- .readthedocs.yml
At OFC I was talking with the OpenROADM people, and it turned out that our docs stopped rendering properly at RTD. It turned out that the build started skipping the bindep.txt file at some (unknown) point in time.
Reported-by: Aparaajitha G L <aparaajitha.gomathinayakamlatha@utdallas.edu>
> docs: fix graphs on RTD
