gnpy/__init__.py, setup.py
include gnpy functionality imports into __init__.py, fix requirements to include scipy, numpy
=> Fix gnpy packaging

examples/OperatorInputNetworkv3.json
JSON file pull request as discussed on Tuesday
Signed-off-by: Jean-Luc Auge <jeanluc.auge@orange.com>
=> JSON file based on Orange operator typical input

contributors.md
=> updated Contributors list

README.rst, examples/transmission_main_example.py, tests/amplifier_test.py, tests/test_network.json
- Add Instructions section in README.rst
- Remove unwanted debug comments in transmission_main_example.py
- Add tests/ path in amplifier_test.py when reading config json files so that tests can be run from the directory root (gnpy/): this way they can be setup and built by Travis CI.
=> README.rst Instructions and tests path for CI

README.rst
Fixes broken hyperlinks in README.
=> fixed README broken hyperlinks

examples/convert.py, examples/eqpt_config.json, examples/transmission_main_example.py, gnpy/core/equipment.py, gnpy/core/info.py, gnpy/core/network.py
checking and bringing the refactor merge up to date
next step: make the tests work with the new class structure
=> Refactor merge 2

Excel_userguide.rst, README.rst, examples/create_eqpt_sheet.py, examples/meshTopologyExampleV2_services.json, examples/path_requests_run.py, examples/write_path_jsontocsv.py, gnpy/core/request.py
In this PR I have processed Issue95 + added output on the results generated by path_request_run (in accumulated metrics) and added a program that convert the json output format into a CSV  to ease demo
=> User guide improvement

gnpy/core/equipment.py
Minor proposed refactoring in equipment.py. For example I didn't understand why in the double for loop in `equipment_from_json`, the references to `key` were in the inner loop. Also, I thought the use of `lambda` seemed unnecessary.
=> Equipment refactoring

examples/convert_service_sheet.py, examples/create_eqpt_sheet.py, examples/path_requests_run.py, examples/write_path_jsontocsv.py, gnpy/core/convert.py, gnpy/core/equipment.py, gnpy/core/service_sheet.py, gnpy/core/utils.py, tests/compare.py, tests/test_amplifier.py, tests/test_parser.py, tests/test_propagation.py
Fix UTF-8 JSON encoding issues referenced in #139 & #140
=> Fix encoding issues

gnpy/core/equipment.py
Simplification of automatic_spacing function. It should do the same thing.
=> Simplify automatic spacing

examples/path_requests_run.py, gnpy/core/request.py
Add a couple of missing imports resulting in `NameError`.
=> add a couple of missing imports

examples/path_requests_run.py, gnpy/core/service_sheet.py
Fix a couple of remaining utf-8 encoding issues.
See PR #142  and issue #163.
=> fix utf-8 encoding

README.rst
Kindly, few minor details modified. I also mention: Additional details are provided by doing ``transmission_main_example.py -h``.
=> Few minor details and typos in README

gnpy/core/elements.py
Proposed fix for #179 using `numpy.divide` to handle division by zero (resulting in `inf`) in OSNR calculations.
=> Fix OSNR calculation when ASE or NLI is zero

examples/transmission_main_example.py
=> improve power range handling - revised version

gnpy/core/node.py
Change to node.py to fix return value error in *coords* property which was intended to build a tuple from two values for latitude and longitude.
=> fix for issue #190

README.rst
Correct the default nodes for CORONET example.
=> Correct README 

Excel_userguide.rst, README.rst, json_structure_description.rst
Signed-off-by: Esther LE ROUZIC <esther.lerouzic@orange.com>
=> more precise description on README for v1.1

gnpy/core/network.py, gnpy/core/request.py
- minor corrections in auto_design
- EOL is now added only once when fusing several fiber spans ('FUSED' in topology)
- code clean up (f.e. replace map & filter wiht comprehension list)
- better Raman support 
- on min gain requirements
- display warning when importing raman eqpt that does not respect the fiber max lineic loss for Raman
rebased on Esther PR #223
=> Auto design3

gnpy/core/elements.py, gnpy/core/request.py, gnpy/core/service_sheet.py
In this PR I have corrected : 
- an exception KeyError type in service sheet that was not correctly catched  in the print:
-> changed to  Request.mode instead of Requestmode (not defined at this point)
- selection of modes did not respect min spacing criterium:
constraint added
+ a improvment on the std out of transmission main to shoaw SNR in 0.1 nm
Could you please review this code and merge  ?
=> correction of 2 bugs

gnpy/core/convert.py, gnpy/core/equipment.py
Simple bugfixes for things that I think are buggy. These were pointed out by some newly added automated tools.
=> Trivial bugfixes

.codecov.yml
...so that our shiny feature branch does not have broken docs.
=> Merge master into develop

.travis.yml, README.rst, examples/edfa_model/amplifier_models_description.rst, json_structure_description.rst
=> docs: fix RST formatting and introduce CI coverage

README.rst
This was suggested by @EstherLerouzic  on today's PSE group call.
@ggrammel , @diegolaunch , I would appreciate your vote here as well. (I'll merge this afterwards.)
=> Encourage people to join us and to join the VCs

.travis.yml, gnpy/core/elements.py, gnpy/core/node.py
...and increase the CI coverage as well while I'm at this.
=> Python: do not use a mutable default value

.travis.yml
This is due to travis-ci/travis-ci@7422.
=> Travis: Docker: Fix version numbers

setup.py
=> update version setup.py

.gitignore, AUTHORS.rst, README.rst, examples/sim_params.json, examples/transmission_main_example.py, gnpy/core/elements.py, gnpy/core/exceptions.py, gnpy/core/network.py, gnpy/core/node.py, gnpy/core/parameters.py, gnpy/core/science_utils.py, gnpy/core/service_sheet.py, json_structure_description.rst, tests/data/sim_params.json, tests/data/testTopology_auto_design_expected.json, tests/data/test_sim_params.json, tests/test_parameters.py, tests/test_propagation.py, tests/test_science_utils.py
This is a cleaned-up version of #319; the cleanup/squashing was done by @EstherLerouzic. I went over the result and tried to give proper credits to all contributors, hence the `Co-authored-by` headers.
=> Polito's Fiber paramter refactoring

examples/path_requests_run.py, gnpy/core/request.py, tests/test_disjunction.py
I've rewritten history of PRs #337 and #339 to squash together changes which are "just fixups", and on the other hand to separate out stuff which -- in my opinion -- is better done in an extra commit. (`git checkout -p` was very helpful for this).
The end result passes all tests and is not different from the #339's head after merge to develop. Thanks to @EstherLerouzic for the actual change.
=> Cleaned-up PRs #337 and #339

tests/test_amplifier.py
2 commits to address issues #324 and #321
=> Correction test amplifier

.travis.yml, docs/conf.py, docs/source/modules.rst, gnpy/core/elements.py, gnpy/core/utils.py, tox.ini
Let Travis-CI run [this change on Gerrit](https://review.gerrithub.io/c/Telecominfraproject/oopt-gnpy/+/488042). See the change on Gerrit for details.
=> Run Travis-CI for Gerrit change 488042

.github/workflows/main.yml, setup.cfg
Let's give the GitHub CI a try before this gets merged.
=> Python 3.10

.github/workflows/main.yml
...which obviously need to go via GitHub for a proper testing.
=> CI: improvements for GitHub
